## Shape changing

In [1]:
import numpy as np

arr = np.random.randint(1,100, size =(10,5))
print(arr)
print(arr.shape)
arr_reshaped = arr.reshape(5,10)
print(arr_reshaped)
print(arr_reshaped.shape)

[[87 47 64 46 88]
 [53 97 18 30 57]
 [96 39 45 59 41]
 [35 59 25 19 27]
 [70 63 31 29 18]
 [35 33 94 84 69]
 [60 34 29 27 13]
 [95 19 46  4 57]
 [58 97  5 83 35]
 [26 18 16 13 14]]
(10, 5)
[[87 47 64 46 88 53 97 18 30 57]
 [96 39 45 59 41 35 59 25 19 27]
 [70 63 31 29 18 35 33 94 84 69]
 [60 34 29 27 13 95 19 46  4 57]
 [58 97  5 83 35 26 18 16 13 14]]
(5, 10)


##Concatenate 

In [4]:
a= np.array([[1,2,3],
               [4,5,6]])
b = np.array([[7,8,9],
               [10,11,12]])
con_row = np.concatenate((a,b),axis=0) # row wise 

print(con_row)

con_col = np.concatenate((a,b), axis = 1) # column wise 

print(con_col)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


##Transpose

In [5]:
mat = np.array([[10,20,30],
                [30,40,50]
               ])


transpose = mat.T

print(transpose) 

[[10 30]
 [20 40]
 [30 50]]


## Split Array

In [ ]:


a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3) 



print(splitted_array)

[3 7 5 5 3 5 5 3 8 5]
[array([3, 7, 5, 5]), array([3, 5, 5]), array([3, 8, 5])]


##arithmetic operator and mathematical functions

In [7]:
x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ]) 

add = np.add(x,y) 
print(add)

sub = x-y 
print(sub)

mul = x*y 
print(mul) 

div = x/y 
print(div) 

remainder = x % y

print(remainder) 

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


### mathematical function 

In [8]:
# trigonometry 

# sin , cos , tan takes values in radian 

sin_val = np.sin(x)
print(sin_val) 

cos_val = np.cos(x)
print(cos_val) 

deg_con = np.rad2deg(x)
print(deg_con)

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [9]:
#log
x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x) 
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [12]:
x = np.array([ 10 , 8 , 16 , 100 ])
s = np.sum(x)
print(s)

#prefix sum 
cumul =np.cumsum(x)
print(cumul)

134
[ 10  18  34 134]


##broadCasting

In [13]:

x = np.array([ 10 , 8 , 16 , 100 ])

result = x + 2 


print(result)
matrix = np.array([[10,20,30],
                [30,40,50]
               ])


result = matrix + 2 

print(result)

[ 12  10  18 102]
[[12 22 32]
 [32 42 52]]


##Logical Function

In [14]:
x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ]) 

greater_than = x>y 

print(greater_than)

equal = x==y 

print(equal) 


print(np.all(greater_than)) 

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


##Sorting

In [15]:
#inplace 
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z) 

z.sort()

print(z)

[ 10   8  16 100]
[  8  10  16 100]


##Searching

In [16]:
# np.where( condition , x , y ) if true x , otherwise replace with y 

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array 
print(arr)

(array([1], dtype=int64),)
[ 10   0  16 100]
