In [ ]:
import numpy as np

# 1d numpy array
arr = np.array([1, 2, 3, 4, 5])

# 2d numpy array
arr2 = np.array(
    [    #col
        [1, 2, 3], #row
        [4, 5, 6],
    ]
)

# 3d numpy array
arr3 = np.array(
    [
        [
            [1, 2, 3],[4, 5, 6]
        ],

        [
            [2, 4, 6],[7, 8, 9],
        ]
    ]
)

print(type(arr3))

<class 'numpy.ndarray'>


##Array Attributes

In [16]:
#dimension

# print(arr.ndim)
# print(arr2.ndim)
# print(arr3.ndim)


#shape

print(arr.shape) #(c)
print(arr2.shape) #(r,c)
print(arr3.shape) #(f,r,c)


#data type

print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size

print(arr.size)
print(arr2.size)
print(arr3.size)


(5,)
(2, 3)
(2, 2, 3)
int32
int32
int32
5
6
12


##ndArray Data Type

In [ ]:
arr = np.array([1,2,3])
print(arr.dtype)


arr = np.array([1.5,3,2,6]) #upcasted to float
print(arr.dtype)

arr = np.array([1,2,3,4,True,'tanjid'])
print(arr.dtype)  #upcasted to string

int32
float64
<U11


##Selecting a data type for an Numpy Array

In [ ]:
arr = np.array([1,2,3],dtype=np.int64) #method 1 to select data type
print(arr.dtype)

arr = arr.astype(np.int32) #method 2 choose data 
print(arr.dtype)

int64
int32


##ndArray Creation from existing data 

In [25]:
import numpy as np

# From List
lst = [1,2,3,4,5,6]

arr = np.array(lst,dtype=np.int32)
# print(arr)
# print(type(arr))
# print(arr.dtype)

# from mixed value
mixed_lst = [1,2,3,4,5,6,'tanjid']
arr = np.array(mixed_lst)

# print(arr)
# print(type(arr)) #convert dtype to string 
# print(arr.dtype)

# tuple

tuple = (1,2,3,4,5,6)
arr = np.array(tuple,dtype=np.int64)
# print(arr)
# print(type(arr))
# print(arr.dtype)

#set
set = {1,2,3,4,5,6}
# arr = np.array(set)
# print(arr)
# print(type(arr))
# print(arr.dtype) #when we create np array from set it dtype will be object type


#dictionary

dict  = {"a":1,"b":2,"c":3}
arr= np.array(dict)
# print(arr)
# print(type(arr))
# print(arr.dtype) # when we give full dict then dtype will be object

arr = np.array(list(dict.values()))

# print(arr)
# print(type(arr))
# print(arr.dtype) 

arr = np.array(list(dict.keys()))

# print(arr)
# print(type(arr))
# print(arr.dtype) # when we give full dict then dtype will be object

arr = np.array(list(dict.items()))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[['a' '1']
 ['b' '2']
 ['c' '3']]
<class 'numpy.ndarray'>
<U11
(3, 2)
2
6


##Creating ndarray from scratch

In [2]:
import numpy as np

#zeros

arr = np.zeros((3,3))  #row,col create np array based on given shape
# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr2 = np.zeros_like(arr)
# print(arr2)
# print(type(arr2))
# print(arr2.dtype)
# print(arr2.shape)
# print(arr2.ndim)
# print(arr2.size)


#ones

arr3 = np.ones((3,3))
# print(arr3)
# print(type(arr3))
# print(arr3.dtype)
# print(arr3.shape)
# print(arr3.ndim)
# print(arr3.size)

arr4 = np.ones_like(arr3) #create array like arr3
# print(arr4)
# print(type(arr4))
# print(arr4.dtype)
# print(arr4.shape)
# print(arr4.ndim)
# print(arr4.size)

#full
arr = np.full((4,3),1)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)



[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int32
(4, 3)
2
12


##Array creation with random values

In [5]:
# np.random.rand(shape) 

arr = np.random.rand(3,3)
# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

# np.random.randint(start,end, shape) 
arr = np.random.randint(1,10,(3,3))
# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

# np.random.uniform(start,end, shape) 

arr = np.random.uniform(1,10,(3,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)



[[4.86967582 2.17278145 1.72195338]
 [4.52686189 7.27171852 8.74359767]
 [7.56559008 3.01282404 6.85125607]]
<class 'numpy.ndarray'>
float64
(3, 3)
2
9


##Array Creation With Range Function

In [9]:
# np.arange(first , end , step ) 

arr = np.arange(1,10,2)
# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

# np.linspace(start , end(included) , steps )

arr = np.linspace(1,10,5)
# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


# np.logspace(start , end(included) , steps )

arr = np.logspace(1,10,5)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)



[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]
<class 'numpy.ndarray'>
float64
(5,)
1
5


##creating matrix for Linear algebra

In [13]:
diagonal_mat = np.diag([1,2,3])


# print(diagonal_mat)

identity_mat = np.eye(3)
print(identity_mat)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##indexing and slicing

In [20]:
#indexing

arr = np.array([1,2,3,4,5,6])

arr2 = np.array(
    [

    [1,2,3],
    [4,5,6]
     
     
     ]
    
    
    )

print(arr[0])
print(arr2[1][2])



1
6


In [ ]:
# 1DSlicing
# Syntax : arr[start:end:step] 

arr = np.array([1,2,3,4,5,6])

print(arr[1:4:2])

#modified array value

arr[0] = 100
print(arr)

[2 4]
[100   2   3   4   5   6]


In [27]:
#2D Array Slicing
#Syntax : arr[row_start:row_end:step , col_start:col_end:step]

arr = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)



# print(arr[1:3,1:3])

#get a column

col_0 = arr[:,0:1]

print(col_0)

[[1]
 [4]
 [7]]


##advance indexing

In [30]:
arr = np.array([ 10 , 20 ,30 ,40 ]) 

values = arr[[0,3,1]]

print(values)

[10 40 20]


In [ ]:
arr = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)


values = arr[[1,2],[0,2]]


print(values)

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3